-- Script para crear las tablas de Recursos Humanos
-- Ejecutar en la base de datos local o en Supabase (si usas Supabase)

-- Tabla de datos adicionales de empleados
CREATE TABLE IF NOT EXISTS HR_EMPLOYEES (
    ID VARCHAR(255) PRIMARY KEY,
    EMPLOYEE_CODE VARCHAR(64),
    DEPARTMENT VARCHAR(100),
    POSITION_TITLE VARCHAR(100),
    CONTRACT_TYPE VARCHAR(60),
    STATUS VARCHAR(40),
    HIRE_DATE TIMESTAMP,
    PAYROLL_FREQUENCY VARCHAR(40),
    BASE_SALARY DOUBLE PRECISION DEFAULT 0.0,
    COMMISSION_RATE DOUBLE PRECISION DEFAULT 0.0,
    TRANSPORT_ALLOWANCE DOUBLE PRECISION DEFAULT 0.0,
    OTHER_ALLOWANCES DOUBLE PRECISION DEFAULT 0.0,
    BONUS_AMOUNT DOUBLE PRECISION DEFAULT 0.0,
    DEDUCTION_RATE DOUBLE PRECISION DEFAULT 9.0,
    PENSION_TYPE VARCHAR(100),
    HEALTH_INSURANCE VARCHAR(100),
    SOCIAL_SECURITY_ID VARCHAR(100),
    BANK_NAME VARCHAR(100),
    BANK_ACCOUNT VARCHAR(100),
    TAX_ID VARCHAR(100),
    EMERGENCY_CONTACT VARCHAR(255),
    NOTES VARCHAR(2000),
    FOREIGN KEY (ID) REFERENCES people(ID)
);

-- Tabla de historial de nómina
CREATE TABLE IF NOT EXISTS HR_PAYROLL (
    ID VARCHAR(255) PRIMARY KEY,
    EMPLOYEE_ID VARCHAR(255),
    PERIOD_LABEL VARCHAR(120),
    PERIOD_START TIMESTAMP,
    PERIOD_END TIMESTAMP,
    PAYMENT_DATE TIMESTAMP,
    BASE_AMOUNT DOUBLE PRECISION DEFAULT 0.0,
    ALLOWANCES DOUBLE PRECISION DEFAULT 0.0,
    BONUS_AMOUNT DOUBLE PRECISION DEFAULT 0.0,
    GROSS_AMOUNT DOUBLE PRECISION,
    COMMISSIONS DOUBLE PRECISION DEFAULT 0.0,
    DEDUCTIONS DOUBLE PRECISION DEFAULT 0.0,
    NET_AMOUNT DOUBLE PRECISION,
    PAYMENT_METHOD VARCHAR(60),
    STATUS VARCHAR(40),
    NOTES VARCHAR(2000),
    PROCESSED_BY VARCHAR(255),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES people(ID)
);
